export const NIGERIAN_BANKS = [
  'Access Bank',
  'Branch International Bank',
  'Citibank Nigeria',
  'Ecobank Nigeria',
  'FairMoney Microfinance Bank',
  'Fidelity Bank',
  'First Bank of Nigeria',
  'First City Monument Bank',
  'Globus Bank',
  'Guaranty Trust Bank',
  'Heritage Bank',
  'Jaiz Bank',
  'Keystone Bank',
  'Kuda Bank',
  'Lotus Bank',
  'Mkobo Microfinance Bank',
  'Moniepoint Microfinance Bank',
  'Nova Merchant Bank',
  'Optimus Bank',
  'Opay Bank',
  'Page MFBank',
  'Parallex Bank',
  'PremiumTrust Bank',
  'Providus Bank',
  'Rand Merchant Bank',
  'Signature Bank',
  'Sparkle Bank',
  'Stanbic IBTC Bank',
  'Standard Chartered Bank',
  'Sterling Bank',
  'SunTrust Bank',
  'Taj Bank',
  'Titan Trust Bank',
  'Union Bank of Nigeria',
  'United Bank for Africa',
  'Unity Bank',
  'VFD Microfinance Bank',
  'Wema Bank',
  'Zenith Bank',
] as const;

export type NigerianBankName = (typeof NIGERIAN_BANKS)[number];