import React from 'react';
import { Text, View, StyleSheet } from 'react-native';
import * as LucideIcons from 'lucide-react-native';

// Map Ionicons-style names to Lucide icon names
const ioniconsToLucideMap: Record<string, string> = {
  // Navigation
  'arrow-back': 'ArrowLeft',
  'arrow-forward': 'ArrowRight',
  'arrow-left': 'ArrowLeft',
  'arrow-right': 'ArrowRight',
  'chevron-back': 'ChevronLeft',
  'chevron-forward': 'ChevronRight',
  'chevron-left': 'ChevronLeft',
  'chevron-right': 'ChevronRight',
  'chevron-up': 'ChevronUp',
  'chevron-down': 'ChevronDown',
  'close': 'X',
  'close-circle': 'XCircle',
  'x-circle': 'XCircle',
  
  // Status
  'check': 'Check',
  'checkmark': 'Check',
  'check-circle': 'CheckCircle',
  'checkmark-circle': 'CheckCircle',
  'checkmark-circle-outline': 'CheckCircle2',
  'check-check': 'CheckCheck',
  'check-square': 'CheckSquare',
  'alert-circle': 'AlertCircle',
  'alert-circle-outline': 'AlertCircle',
  'alert-triangle': 'AlertTriangle',
  'information-circle': 'Info',
  'information-circle-outline': 'Info',
  'info': 'Info',
  'help-circle': 'HelpCircle',
  'help-circle-outline': 'HelpCircle',
  'warning': 'AlertTriangle',
  'warning-outline': 'AlertTriangle',
  
  // People
  'person': 'User',
  'person-outline': 'User',
  'user': 'User',
  'people': 'Users',
  'people-outline': 'Users',
  'users': 'Users',
  
  // Time & Calendar
  'calendar': 'Calendar',
  'calendar-outline': 'Calendar',
  'time': 'Clock',
  'time-outline': 'Clock',
  'clock': 'Clock',
  
  // Finance
  'cash': 'Banknote',
  'cash-outline': 'Banknote',
  'banknote': 'Banknote',
  'card': 'CreditCard',
  'card-outline': 'CreditCard',
  'credit-card': 'CreditCard',
  'wallet': 'Wallet',
  'wallet-outline': 'Wallet',
  'receipt': 'Receipt',
  'receipt-outline': 'Receipt',
  
  // Shopping
  'cart': 'ShoppingCart',
  'cart-outline': 'ShoppingCart',
  'bag': 'ShoppingBag',
  'bag-outline': 'ShoppingBag',
  
  // Business
  'briefcase': 'Briefcase',
  'briefcase-outline': 'Briefcase',
  'business': 'Building2',
  'business-outline': 'Building2',
  'building': 'Building2',
  'building-outline': 'Building2',
  
  // Objects
  'gift': 'Gift',
  'gift-outline': 'Gift',
  'rocket': 'Rocket',
  'rocket-outline': 'Rocket',
  'diamond': 'Gem',
  'diamond-outline': 'Gem',
  'cube': 'Box',
  'cube-outline': 'Box',
  'trophy': 'Trophy',
  'trophy-outline': 'Trophy',
  'star': 'Star',
  'star-outline': 'Star',
  'coffee': 'Coffee',
  'coffee-outline': 'Coffee',
  'car': 'Car',
  'car-outline': 'Car',
  'monitor': 'Monitor',
  'monitor-outline': 'Monitor',
  'wrench': 'Wrench',
  'wrench-outline': 'Wrench',
  'megaphone': 'Megaphone',
  'megaphone-outline': 'Megaphone',
  'zap': 'Zap',
  'zap-outline': 'Zap',
  'more-horizontal': 'MoreHorizontal',
  'more-vertical': 'MoreVertical',
  
  // Actions
  'add': 'Plus',
  'plus': 'Plus',
  'add-circle': 'PlusCircle',
  'add-circle-outline': 'PlusCircle',
  'remove': 'Minus',
  'minus': 'Minus',
  'remove-circle': 'MinusCircle',
  'trash': 'Trash2',
  'trash-outline': 'Trash2',
  'trash-2': 'Trash2',
  'create': 'Edit',
  'create-outline': 'Edit',
  'settings': 'Settings',
  'settings-outline': 'Settings',
  'search': 'Search',
  'search-outline': 'Search',
  'refresh': 'RefreshCw',
  'refresh-outline': 'RefreshCw',
  'sync': 'RefreshCw',
  'sync-outline': 'RefreshCw',
  'download': 'Download',
  'download-outline': 'Download',
  'upload': 'Upload',
  'upload-outline': 'Upload',
  'share': 'Share2',
  'share-outline': 'Share2',
  'copy': 'Copy',
  'copy-outline': 'Copy',
  
  // Communication
  'mail': 'Mail',
  'mail-outline': 'Mail',
  'call': 'Phone',
  'call-outline': 'Phone',
  'phone': 'Phone',
  'phone-outline': 'Phone',
  'chatbubble': 'MessageCircle',
  'chatbubble-outline': 'MessageCircle',
  'notifications': 'Bell',
  'notifications-outline': 'Bell',
  'smartphone': 'Smartphone',
  'smartphone-outline': 'Smartphone',
  
  // Navigation/Location
  'home': 'Home',
  'home-outline': 'Home',
  'location': 'MapPin',
  'location-outline': 'MapPin',
  'navigate': 'Navigation',
  'navigate-outline': 'Navigation',
  'map': 'Map',
  'map-outline': 'Map',
  
  // Documents
  'document': 'FileText',
  'document-outline': 'FileText',
  'file-text': 'FileText',
  'documents': 'Files',
  'documents-outline': 'Files',
  'files': 'Files',
  'folder': 'Folder',
  'folder-outline': 'Folder',
  'list': 'List',
  'list-outline': 'List',
  'clipboard': 'Clipboard',
  'clipboard-outline': 'Clipboard',
  
  // Media
  'image': 'Image',
  'image-outline': 'Image',
  'camera': 'Camera',
  'camera-outline': 'Camera',
  'play': 'Play',
  'play-outline': 'Play',
  'pause': 'Pause',
  'pause-outline': 'Pause',
  
  // Misc
  'eye': 'Eye',
  'eye-outline': 'Eye',
  'eye-off': 'EyeOff',
  'eye-off-outline': 'EyeOff',
  'lock-closed': 'Lock',
  'lock-closed-outline': 'Lock',
  'lock-open': 'Unlock',
  'lock-open-outline': 'Unlock',
  'key': 'Key',
  'key-outline': 'Key',
  'link': 'Link',
  'link-outline': 'Link',
  'heart': 'Heart',
  'heart-outline': 'Heart',
  'thumbs-up': 'ThumbsUp',
  'thumbs-up-outline': 'ThumbsUp',
  'thumbs-down': 'ThumbsDown',
  'thumbs-down-outline': 'ThumbsDown',
  'flash': 'Zap',
  'flash-outline': 'Zap',
  'shield': 'Shield',
  'shield-outline': 'Shield',
  'shield-checkmark': 'ShieldCheck',
  'shield-checkmark-outline': 'ShieldCheck',
  'analytics': 'BarChart3',
  'analytics-outline': 'BarChart3',
  'trending-up': 'TrendingUp',
  'trending-up-outline': 'TrendingUp',
  'trending-down': 'TrendingDown',
  'trending-down-outline': 'TrendingDown',
  'log-out': 'LogOut',
  'log-out-outline': 'LogOut',
  'log-in': 'LogIn',
  'log-in-outline': 'LogIn',
  'exit': 'LogOut',
  'exit-outline': 'LogOut',
  'menu': 'Menu',
  'menu-outline': 'Menu',
  'ellipsis-horizontal': 'MoreHorizontal',
  'ellipsis-vertical': 'MoreVertical',
  'options': 'Settings2',
  'options-outline': 'Settings2',
  'filter': 'Filter',
  'filter-outline': 'Filter',
  'funnel': 'Filter',
  'funnel-outline': 'Filter',
  'expand': 'Maximize2',
  'expand-outline': 'Maximize2',
  'contract': 'Minimize2',
  'contract-outline': 'Minimize2',
  'grid': 'Grid',
  'grid-outline': 'Grid',
  'layers': 'Layers',
  'layers-outline': 'Layers',
  'infinite': 'Infinity',
  'infinite-outline': 'Infinity',
  'globe': 'Globe',
  'globe-outline': 'Globe',
  'cloud': 'Cloud',
  'cloud-outline': 'Cloud',
  'cloud-download': 'CloudDownload',
  'cloud-download-outline': 'CloudDownload',
  'cloud-upload': 'CloudUpload',
  'cloud-upload-outline': 'CloudUpload',
  'wifi': 'Wifi',
  'wifi-outline': 'Wifi',
  'bluetooth': 'Bluetooth',
  'bluetooth-outline': 'Bluetooth',
  'qr-code': 'QrCode',
  'qr-code-outline': 'QrCode',
  'barcode': 'Barcode',
  'barcode-outline': 'Barcode',
  'print': 'Printer',
  'print-outline': 'Printer',
  'save': 'Save',
  'save-outline': 'Save',
  'attach': 'Paperclip',
  'attach-outline': 'Paperclip',
  'pricetag': 'Tag',
  'pricetag-outline': 'Tag',
  'pricetags': 'Tags',
  'pricetags-outline': 'Tags',
  'at': 'AtSign',
  'at-outline': 'AtSign',
  'hash': 'Hash',
  'hash-outline': 'Hash',
  'code': 'Code',
  'code-outline': 'Code',
  'terminal': 'Terminal',
  'terminal-outline': 'Terminal',
  'bug': 'Bug',
  'bug-outline': 'Bug',
  'construct': 'Wrench',
  'construct-outline': 'Wrench',
  'hammer': 'Hammer',
  'hammer-outline': 'Hammer',
  'build': 'Hammer',
  'build-outline': 'Hammer',
  'bulb': 'Lightbulb',
  'bulb-outline': 'Lightbulb',
  'fitness': 'Activity',
  'fitness-outline': 'Activity',
  'pulse': 'Activity',
  'pulse-outline': 'Activity',
  'medkit': 'Cross',
  'medkit-outline': 'Cross',
  'sparkles': 'Sparkles',
  'sparkles-outline': 'Sparkles',
  
  // Additional document icons
  'document-text': 'FileText',
  'document-text-outline': 'FileText',
  'reader': 'BookOpen',
  'reader-outline': 'BookOpen',
  'book': 'Book',
  'book-outline': 'Book',
  'bookmark': 'Bookmark',
  'bookmark-outline': 'Bookmark',
  'newspaper': 'Newspaper',
  'newspaper-outline': 'Newspaper',
  
  // Additional check/done icons
  'checkmark-done': 'CheckCheck',
  'checkmark-done-outline': 'CheckCheck',
  'checkbox': 'CheckSquare',
  'checkbox-outline': 'CheckSquare',
  'square': 'Square',
  'square-outline': 'Square',
  
  // Additional search icons
  'search-circle': 'SearchCheck',
  'search-circle-outline': 'SearchCheck',
  
  // Additional common icons
  'moon': 'Moon',
  'moon-outline': 'Moon',
  'sunny': 'Sun',
  'sunny-outline': 'Sun',
  'partly-sunny': 'CloudSun',
  'partly-sunny-outline': 'CloudSun',
  'rainy': 'CloudRain',
  'rainy-outline': 'CloudRain',
  'snow': 'Snowflake',
  'snow-outline': 'Snowflake',
  'thermometer': 'Thermometer',
  'thermometer-outline': 'Thermometer',
  'water': 'Droplet',
  'water-outline': 'Droplet',
  'battery-full': 'BatteryFull',
  'battery-half': 'BatteryMedium',
  'battery-low': 'BatteryLow',
  'battery-dead': 'Battery',
  'power': 'Power',
  'power-outline': 'Power',
  'reload': 'RotateCw',
  'reload-outline': 'RotateCw',
  'repeat': 'Repeat',
  'repeat-outline': 'Repeat',
  'shuffle': 'Shuffle',
  'shuffle-outline': 'Shuffle',
  'mic': 'Mic',
  'mic-outline': 'Mic',
  'mic-off': 'MicOff',
  'mic-off-outline': 'MicOff',
  'volume-high': 'Volume2',
  'volume-medium': 'Volume1',
  'volume-low': 'Volume',
  'volume-mute': 'VolumeX',
  'volume-off': 'VolumeX',
  'hand-left': 'Hand',
  'hand-left-outline': 'Hand',
  'hand-right': 'Hand',
  'hand-right-outline': 'Hand',
  'finger-print': 'Fingerprint',
  'finger-print-outline': 'Fingerprint',
  'scan': 'Scan',
  'scan-outline': 'Scan',
};

const emojiMap: Record<string, string> = {
  Home: '🏠',
  User: '👤',
  Plus: '➕',
  Key: '🔑',
  Search: '🔍',
  List: '📋',
  ShoppingCart: '🛒',
  Wallet: '💳',
  Check: '✅',
  BarChart: '📊',
  Clipboard: '📋',
  Calendar: '📅',
  Clock: '⏱️',
  ChevronRight: '→',
  DollarSign: '💰',
  CreditCard: '💳',
};

export default function Icon({
  name,
  size = 20,
  color = '#000',
  style,
}: {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}) {
  // Convert Ionicons-style name to Lucide name if needed
  const lucideName = ioniconsToLucideMap[name] || name;
  
  // Try to get the Lucide icon component
  // @ts-ignore - dynamic access on LucideIcons
  const Comp = (LucideIcons as any)[lucideName];
  if (Comp) {
    // lucide icons accept color/width/height
    return <Comp color={color} width={size} height={size} style={style as any} />;
  }

  // Fallback to emoji if no Lucide icon found
  const emoji = emojiMap[lucideName] ?? emojiMap[name] ?? '❔';
  return (
    <View style={[styles.container, style]}>
      <Text style={{ fontSize: size * 0.9 }}>{emoji}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { alignItems: 'center', justifyContent: 'center' },
});
